language: python
python:
  - "3.7"
  - "nightly"
install:
  - pip install -e .
  - pip install coverage
script:
  - coverage run --branch --source hmrc setup.py test
  - coverage report --show-missing
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  skip_existing: true
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
